### ISSUE TITLE
Conflict with Avadas "Fusion Page Builder"

### ISSUE THREAD

**Issue by Takkster** [benjaminprojas/wp-editor#40]
Hi Ben,

thanks for the plugin, have been using it on many of my installations. There is a serious bug which I could just replicate:
With the **Avada theme** (4.0.2 all patches active, child theme active) comes a page builder called "**Fusion Page Builder**". When the WP-Editor plugin (1.2.6) is active, Fusion Page Builder **can't save anymore. Practically all changes made via Fusion on a page or post are lost when saving.** 

I could replicate this issue on 3 of my pages. 
- active plugins: WP-Editor and Fusion Core (necessary for the Fusion Page Builder to work)
- issue persists with the default twentysixteen theme!
- no saving issues with the default WP Post Editor

**Comment by benjaminprojas** [comment]
@Takkster,

Thanks for the information.  I see that Avada is available for purchase.  It is difficult to troubleshoot issues with plugins or themes that are paid since I can't get a hold of them without purchasing.  This is a free product so its hard to justify that expense.  I will do my best to see if I can figure out a way to resolve this conflict (and with Visual Composer) however I don't have a timeline for troubleshooting and putting out a fix at this point.

**Comment by Takkster** [comment]
@benjaminprojas 
I'll contact you via mail if that's ok, maybe we can work something out.

**Comment by Takkster** [comment]
I just made a test on one of my pages, saving with Avada Fusion Builder seems to work again.
