### ISSUE TITLE
Unable to add media file to Text editor

### ISSUE THREAD

**Issue by alex1278** [benjaminprojas/wp-editor#42]
After plugin update to version 1.2.6, I can't add media to post editor field in Text mode. I always get an error in console: TypeError: element.value is undefined

https://wordpress.org/plugins/wp-editor/
![admin2](https://cloud.githubusercontent.com/assets/15159810/15486846/398af000-2151-11e6-91ea-4469e7db8ee4.jpg)
![admin1](https://cloud.githubusercontent.com/assets/15159810/15486847/398e57b8-2151-11e6-8a3f-ab5f0fcca889.jpg)

**Comment by benjaminprojas** [comment]
@alex1278 thanks for the information!  Can you try deactivating all other plugins and activate only the default theme and see if this fixes the issue?  If it does, try reactivating the plugins one by one (and theme) to see if the issue comes back.

Also, can you let me know which browser and OS are you on?

**Comment by alex1278** [comment]
I have Windows 8. I tested Firefox, Chrome and EI10. I also tested another PC. This error appears in all listed browsers. Yes, I tried to deactivate all plugins and switched 'Twenty Sixteen', but if try to insert media file via media loader in Text mode I get nothing. Visual mode works as usual.

**Comment by benjaminprojas** [comment]
@alex1278 Can you try updating to WP Editor 1.2.6.1 and see if that resolves the issue?

Thanks!

**Comment by alex1278** [comment]
Oh, Yes. Now it is really works. Thank you for your quick response.
